
# tasks file for roles/2PRecuperatorio
- name: Crear grupo GProfesores
  group:
    name: GProfesores
    state: present

- name: Crear grupo GAlumnos
  group:
    name: GAlumnos
    state: present

- name: Crear usuario profesor
  user:
    name: profesor
    groups: GProfesores
    shell: /bin/bash

- name: Crear usuario alumno
  user:
    name: alumno
    groups: GAlumnos
    shell: /bin/bash

